### ISSUE TITLE
Add Here Maps-     Specs satisfying the `here_sdk (from `.symlinks/plugins/here_sdk/ios`)` dependency were found, but     they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by VivianKuKu** [VivianKuKu/CASA0015_Mobile-System_QEOP-IoT#4]
https://developer.here.com/documentation/flutter-sdk-navigate/4.4.0.2/dev_guide/topics/quick-start.html
https://platform.here.com/sdk -> HERE SDK Explore Edition for Flutter

**Comment by VivianKuKu** [comment]
@eduroam-int-dhcp-98-165-47 test_map % Flutter run
Launching lib/main.dart on iPhone 13 mini in debug mode...
/Users/kuchin/6_CASA0015_App/test_map/ios/Runner/Info.plist: Property List error: Found non-key inside
<dict> at line 16 / JSON error: JSON text did not start with array or object and option to allow
fragments not set. around line 1, column 0.
Running pod install...                                             663ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `here_sdk` from `.symlinks/plugins/here_sdk/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only
      performed in repo update
    [!] CocoaPods could not find compatible versions for pod "here_sdk":
      In Podfile:
        here_sdk (from `.symlinks/plugins/here_sdk/ios`)

    Specs satisfying the `here_sdk (from `.symlinks/plugins/here_sdk/ios`)` dependency were found, but
    they required a higher minimum deployment target.

    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317
    :in `raise_error_unless_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299
    :in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297
    :in `unwind_for_conflict'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682
    :in `attempt_to_activate'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254
    :in `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182
    :in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in
    `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:i
    n `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyz
    er.rb:1078:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.r
    b:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyz
    er.rb:1076:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyz
    er.rb:124:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416
    :in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241
    :in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.r
    b:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240
    :in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161
    :in `install!'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.
    rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in
    `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top
    (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

Error running pod install
Error launching application on iPhone 13 mini.

**Comment by VivianKuKu** [comment]
/ios/Podfile

#Uncomment this line to define a global platform for your project
platform :ios, '12.4'  #new add
